[package]
name = "substrate"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Geometric types"
repository = "https://github.com/piot/substrate-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed32 = "0.0.2"
